live_config_reload = true
working_directory = "/home/soleblaze"

[bell]
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "#ff8c00"
index = 16

[[colors.indexed_colors]]
color = "#0088ff"
index = 17

[[colors.indexed_colors]]
color = "#5555ff"
index = 18

[[colors.indexed_colors]]
color = "#555555"
index = 237

[colors.bright]
black = "#808080"
blue = "#1478db"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.cursor]
cursor = "#ffc600"
text = "CellBackground"

[colors.footer_bar]
background = "#1F4662"
foreground = "#fcfcfc"

[colors.hints.end]
background = "#00c5c7"
foreground = "#c7c7c7"

[colors.hints.start]
background = "#3ad900"
foreground = "#c7c7c7"

[colors.normal]
black = "#000000"
blue = "#1478db"
cyan = "#00c5c7"
green = "#3ad900"
magenta = "#ff2c70"
red = "#ff2600"
white = "#c7c7c7"
yellow = "#ffc600"

[colors.primary]
background = "#193549"
foreground = "#fefefe"

[colors.selection]
background = "#ffc600"
text = "#fefefe"

[colors.vi_mode_cursor]
cursor = "#3ad900"
text = "CellBackground"

[debug]
log_level = "Warn"
persistent_logging = false

[font]
normal = { family = "DejaVuSansM Nerd Font Mono" }
size = 16

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"
