tap "charmbracelet/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "siderolabs/talos"
brew "ansible"
brew "ansifilter"
brew "bat"
brew "bat-extras"
brew "binutils"
brew "charmbracelet/tap/mods"
brew "charmbracelet/tap/vhs"
brew "glow"
brew "colima", restart_service: true
brew "difftastic"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "dos2unix"
brew "duf"
brew "dust"
brew "exercism"
brew "eza"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "geeqie"
brew "gimp"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "github"
brew "glances"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "helm"
brew "ipython"
brew "jdupes"
brew "jhead"
brew "jq"
brew "krew"
brew "kubernetes-cli"
brew "mas"
brew "mosh"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node"
brew "packer"
brew "pipx"
brew "prettyping"
brew "procs"
brew "rdfind"
brew "ripgrep"
brew "ruby"
brew "sd"
brew "shellcheck"
brew "siderolabs/talos/talosctl"
brew "starship"
brew "terraform"
brew "tmux"
brew "wget"
brew "yt-dlp"
brew "yq"
brew "xh"
brew "zoxide"
brew "zsh"
brew "zsh-autopair"
brew "zsh-completions"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-vi-mode"
brew "zsh-you-should-use"
cask "1password"
cask "bartender"
cask "devonagent"
cask "devonthink"
cask "discord"
cask "font-dejavu"
cask "font-dejavu-sans-mono-nerd-font"
cask "fujitsu-scansnap-home"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "little-snitch"
cask "meld"
cask "raycast"
cask "screenflow"
cask "secretive"
cask "visual-studio-code"
cask "yubico-yubikey-manager"
mas "Kagi for Safari", id: 1622835804
mas "Bear Markdown Notes", id: 1091189122
mas "MindNode", id: 1289197285
mas "OmniFocus", id: 1542143627
mas "Reeder", id: 1529448980
mas "Screens 4", id: 1224268771
mas "Slack for Desktop", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "TextSniper", id: 1528890965
mas "Tailscale", id: 1475387142
mas "Noir - Dark Mode for Safari", id: 1592917505
mas "Wipr", id: 1320666476
mas "Wireguard", id: 1451685025
mas "Vimari", id: 1480933944
mas "Day One", id: 1055511498
