tap "hidetatz/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "agg"
brew "ansifilter"
brew "asciinema"
brew "bat"
brew "bat-extras"
brew "binutils"
brew "cmake"
brew "colima"
brew "coreutils"
brew "docker"
brew "docker-buildx"
brew "dog"
brew "dos2unix"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git"
brew "git-delta"
brew "git-extras"
brew "glances"
brew "glow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "helm"
brew "ipython"
brew "jhead"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "ncdu"
brew "neovim"
brew "node"
brew "pipx"
brew "virtualenv"
brew "poetry"
brew "pre-commit"
brew "prettyping"
brew "rdfind"
brew "ripgrep"
brew "rust"
brew "sd"
brew "shellcheck"
brew "starship"
brew "tmux"
brew "vale"
brew "viddy"
brew "wget"
brew "xh"
brew "yarn"
brew "yq"
brew "zoxide"
brew "zsh"
brew "zsh-autopair"
brew "zsh-completions"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-vi-mode"
brew "zsh-you-should-use"
brew "hidetatz/tap/kubecolor"
cask "1password"
cask "bartender"
cask "font-dejavu"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "little-snitch"
cask "meld"
cask "obs"
cask "raindropio"
cask "raycast"
cask "screenflow"
cask "secretive"
cask "thingsmacsandboxhelper"
cask "visual-studio-code"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "Moom", id: 419330170
mas "Reeder", id: 1529448980
mas "Save to Raindrop.io", id: 1549370672
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "Things", id: 904280696
mas "Wipr", id: 1320666476
