tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "kudobuilder/tap"
tap "romkatv/powerlevel10k"
brew "ansible-lint"
brew "bat"
brew "bat-extras"
brew "black"
brew "brew-gem"
brew "chart-testing"
brew "codespell"
brew "cookiecutter"
brew "ctags"
brew "dos2unix"
brew "exercism"
brew "fd"
brew "fdupes"
brew "fluxctl"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "glow"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "gopls"
brew "hadolint"
brew "helm"
brew "jdupes"
brew "jhead"
brew "jq"
brew "json-glib"
brew "jsonlint"
brew "kind"
brew "kubernetes-cli"
brew "kubeseal"
brew "kubeval"
brew "kuttl-cli"
brew "krew"
brew "markdownlint-cli"
brew "mas"
brew "mosh"
brew "neovim"
brew "nmap"
brew "node"
brew "node@14"
brew "podman"
brew "powerlevel10k"
brew "pre-commit"
brew "prettier"
brew "prettyping"
brew "rdfind"
brew "ripgrep"
brew "rpm2cpio"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "shfmt"
brew "socat"
brew "stylua"
brew "task"
brew "tig"
brew "tldr"
brew "tmux"
brew "vale"
brew "viddy"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "yq"
brew "zsh-autopair"
brew "zsh-completions"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"
cask "1password"
cask "bartender"
cask "dash"
cask "devonagent"
cask "devonthink"
cask "discord"
cask "font-dejavu"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "hookmark"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "istat-menus"
cask "iterm2"
cask "meld"
cask "obsidian"
cask "omnifocus"
cask "raindropio"
cask "raycast"
cask "secretive"
cask "timing"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "1Password for Safari", id: 1569813296
mas "Dark Noise", id: 1465439395
mas "Day One", id: 1055511498
mas "MindNode", id: 1289197285
mas "OmniOutliner 5", id: 1142578772
mas "Reeder", id: 1529448980
mas "Save to Raindrop.io", id: 1549370672
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "TestFlight", id: 899247664
mas "TextSniper", id: 1528890965
mas "Wipr", id: 1320666476
mas "Wireguard", id: 1451685025
