local keymap = vim.api.nvim_set_keymap

local function notify(cmd)
    return string.format("<cmd>call VSCodeNotify('%s')<CR>", cmd)
end

keymap("n", "<leader>D", notify 'editor.action.revealDefinitionAside', { silent = true })
keymap("n", "<leader>F", notify 'editor.action.formatDocument', { silent = true })
keymap("n", "<leader>P", '"+P', { silent = true })
keymap("n", "<leader>b", notify 'workbench.action.toggleSidebarVisibility', { silent = true })
keymap("n", "<leader>d", notify 'editor.action.showDefinitionPreviewHover', { silent = true })
keymap("n", "<leader>e", notify 'problems.action.open', { silent = true })
keymap("n", "<leader>ff", notify 'workbench.action.quickOpen', { silent = true })
keymap("n", "<leader>fg", notify 'workbench.action.findInFiles', { silent = true })
keymap("n", "<leader>fp", notify 'projectManager.listProjects', { silent = true })
keymap("n", "<leader>fr", notify 'references-view.findReferences', { silent = true })
keymap("n", "<leader>gb", notify 'gitlens.toggleFileBlame', { silent = true })
keymap("n", "<leader>gd", notify 'editor.action.revealDefinition', { silent = true })
keymap("n", "<leader>gi", notify 'editor.action.goToImplementation', { silent = true })
keymap("n", "<leader>gl", notify 'extension.copyGitHubLinkToClipboard', { silent = true })
keymap("n", "<leader>gr", notify 'editor.action.goToReferences', { silent = true })
keymap("n", "<leader>gs", notify 'workbench.action.showAllSymbols', { silent = true })
keymap("n", "<leader>gt", notify 'editor.action.goToTypeDefinition', { silent = true })
keymap("n", "<leader>k", notify 'extension.dash.specific', { silent = true })
keymap("n", "<leader>p", '"+p', { silent = true })
keymap("n", "<leader>rf", notify 'editor.action.refactor', { silent = true })
keymap("n", "<leader>rn", notify 'editor.action.rename', { silent = true })
keymap("n", "<leader>y", '"+y', { silent = true })
keymap("n", "[D", notify 'editor.action.marker.prevInFiles', { silent = true })
keymap("n", "[d", notify 'editor.action.marker.prev', { silent = true })
keymap("n", "]D", notify 'editor.action.marker.nextInFiles', { silent = true })
keymap("n", "]d", notify 'editor.action.marker.next', { silent = true })
keymap("n", "<leader>f", '<Plug>(easymotion-bd-fl)', { silent = true })
keymap("n", "<leader>l", '<Plug>(easymotion-bd-jk)', { silent = true })
keymap("n", "<leader>s", '<Plug>(easymotion-s2)', { silent = true })
keymap("v", "<leader>y", '"+y', { silent = true })
