session: ${PROJECT}
env:
  PROJECT: ${PROJECT}
root: ~/projects/${PROJECT}
windows:
- name: notes
  root: ../notes
  commands:
    - nvim ${PROJECT}.md
- name: code
  commands:
    - nvim
- name: zsh
  commands: []
- name: logged
  commands: []
