device_name = "AT Translated Set 2 keyboard"

# Configure CAPSLOCK as a Dual Role key.
# Holding it produces LEFTCTRL, but tapping it
# will produce ESC.
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[dual_role]]
input = "KEY_TAB"
hold = ["KEY_LEFTMETA"]
tap = ["KEY_TAB"]
