# From: https://github.com/ahmetb/kubectl-aliases
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alias ktn="kubecolor top nodes"
alias ktp="kubecolor top pods"

alias k='kubecolor'

alias ka='kubecolor apply --recursive -f'
alias kd='kubecolor describe'
alias kdall='kubecolor describe --all-namespaces'
alias kdcm='kubecolor describe configmap'
alias kdcmall='kubecolor describe configmap --all-namespaces'
alias kdcml='kubecolor describe configmap -l'
alias kdcmn='kubecolor describe configmap --namespace'
alias kddep='kubecolor describe deployment'
alias kddepall='kubecolor describe deployment --all-namespaces'
alias kddepl='kubecolor describe deployment -l'
alias kddepn='kubecolor describe deployment --namespace'
alias kdf='kubecolor describe --recursive -f'
alias kding='kubecolor describe ingress'
alias kdingall='kubecolor describe ingress --all-namespaces'
alias kdingl='kubecolor describe ingress -l'
alias kdingn='kubecolor describe ingress --namespace'
alias kdl='kubecolor describe -l'
alias kdn='kubecolor describe --namespace'
alias kdno='kubecolor describe nodes'
alias kdnol='kubecolor describe nodes -l'
alias kdns='kubecolor describe namespaces'
alias kdnsall='kubecolor describe namespaces --all-namespaces'
alias kdnsl='kubecolor describe namespaces -l'
alias kdpo='kubecolor describe pods'
alias kdpoall='kubecolor describe pods --all-namespaces'
alias kdpol='kubecolor describe pods -l'
alias kdpon='kubecolor describe pods --namespace'
alias kdsec='kubecolor describe secret'
alias kdsecall='kubecolor describe secret --all-namespaces'
alias kdsecl='kubecolor describe secret -l'
alias kdsecn='kubecolor describe secret --namespace'
alias kdsvc='kubecolor describe service'
alias kdsvcall='kubecolor describe service --all-namespaces'
alias kdsvcl='kubecolor describe service -l'
alias kdsvcn='kubecolor describe service --namespace'
alias kex='kubecolor exec -i -t'
alias kexn='kubecolor exec -i -t --namespace'
alias kg='kubecolor get'
alias kgall='kubecolor get --all-namespaces'
alias kgallojson='kubecolor get --all-namespaces -o=json'
alias kgallowide='kubecolor get --all-namespaces -o=wide'
alias kgallowidesl='kubecolor get --all-namespaces -o=wide --show-labels'
alias kgalloyaml='kubecolor get --all-namespaces -o=yaml'
alias kgallsl='kubecolor get --all-namespaces --show-labels'
alias kgallslowide='kubecolor get --all-namespaces --show-labels -o=wide'
alias kgallslw='kubecolor get --all-namespaces --show-labels --watch'
alias kgallslwowide='kubecolor get --all-namespaces --show-labels --watch -o=wide'
alias kgallw='kubecolor get --all-namespaces --watch'
alias kgallwojson='kubecolor get --all-namespaces --watch -o=json'
alias kgallwowide='kubecolor get --all-namespaces --watch -o=wide'
alias kgallwowidesl='kubecolor get --all-namespaces --watch -o=wide --show-labels'
alias kgallwoyaml='kubecolor get --all-namespaces --watch -o=yaml'
alias kgallwsl='kubecolor get --all-namespaces --watch --show-labels'
alias kgallwslowide='kubecolor get --all-namespaces --watch --show-labels -o=wide'
alias kgc='kubectl config get-contexts'
alias kgcm='kubecolor get configmap'
alias kgcmall='kubecolor get configmap --all-namespaces'
alias kgcmallojson='kubecolor get configmap --all-namespaces -o=json'
alias kgcmallowide='kubecolor get configmap --all-namespaces -o=wide'
alias kgcmalloyaml='kubecolor get configmap --all-namespaces -o=yaml'
alias kgcmallw='kubecolor get configmap --all-namespaces --watch'
alias kgcmallwojson='kubecolor get configmap --all-namespaces --watch -o=json'
alias kgcmallwowide='kubecolor get configmap --all-namespaces --watch -o=wide'
alias kgcmallwoyaml='kubecolor get configmap --all-namespaces --watch -o=yaml'
alias kgcml='kubecolor get configmap -l'
alias kgcmn='kubecolor get configmap --namespace'
alias kgcmojson='kubecolor get configmap -o=json'
alias kgcmojsonall='kubecolor get configmap -o=json --all-namespaces'
alias kgcmojsonl='kubecolor get configmap -o=json -l'
alias kgcmojsonn='kubecolor get configmap -o=json --namespace'
alias kgcmowide='kubecolor get configmap -o=wide'
alias kgcmowideall='kubecolor get configmap -o=wide --all-namespaces'
alias kgcmowidel='kubecolor get configmap -o=wide -l'
alias kgcmowiden='kubecolor get configmap -o=wide --namespace'
alias kgcmoyaml='kubecolor get configmap -o=yaml'
alias kgcmoyamlall='kubecolor get configmap -o=yaml --all-namespaces'
alias kgcmoyamll='kubecolor get configmap -o=yaml -l'
alias kgcmoyamln='kubecolor get configmap -o=yaml --namespace'
alias kgcmw='kubecolor get configmap --watch'
alias kgcmwall='kubecolor get configmap --watch --all-namespaces'
alias kgcmwallojson='kubecolor get configmap --watch --all-namespaces -o=json'
alias kgcmwallowide='kubecolor get configmap --watch --all-namespaces -o=wide'
alias kgcmwalloyaml='kubecolor get configmap --watch --all-namespaces -o=yaml'
alias kgcmwl='kubecolor get configmap --watch -l'
alias kgcmwn='kubecolor get configmap --watch --namespace'
alias kgcmwojson='kubecolor get configmap --watch -o=json'
alias kgcmwojsonall='kubecolor get configmap --watch -o=json --all-namespaces'
alias kgcmwojsonl='kubecolor get configmap --watch -o=json -l'
alias kgcmwojsonn='kubecolor get configmap --watch -o=json --namespace'
alias kgcmwowide='kubecolor get configmap --watch -o=wide'
alias kgcmwowideall='kubecolor get configmap --watch -o=wide --all-namespaces'
alias kgcmwowidel='kubecolor get configmap --watch -o=wide -l'
alias kgcmwowiden='kubecolor get configmap --watch -o=wide --namespace'
alias kgcmwoyaml='kubecolor get configmap --watch -o=yaml'
alias kgcmwoyamlall='kubecolor get configmap --watch -o=yaml --all-namespaces'
alias kgcmwoyamll='kubecolor get configmap --watch -o=yaml -l'
alias kgcmwoyamln='kubecolor get configmap --watch -o=yaml --namespace'
alias kgdep='kubecolor get deployment'
alias kgdepall='kubecolor get deployment --all-namespaces'
alias kgdepallojson='kubecolor get deployment --all-namespaces -o=json'
alias kgdepallowide='kubecolor get deployment --all-namespaces -o=wide'
alias kgdepallowidesl='kubecolor get deployment --all-namespaces -o=wide --show-labels'
alias kgdepalloyaml='kubecolor get deployment --all-namespaces -o=yaml'
alias kgdepallsl='kubecolor get deployment --all-namespaces --show-labels'
alias kgdepallslowide='kubecolor get deployment --all-namespaces --show-labels -o=wide'
alias kgdepallslw='kubecolor get deployment --all-namespaces --show-labels --watch'
alias kgdepallslwowide='kubecolor get deployment --all-namespaces --show-labels --watch -o=wide'
alias kgdepallw='kubecolor get deployment --all-namespaces --watch'
alias kgdepallwojson='kubecolor get deployment --all-namespaces --watch -o=json'
alias kgdepallwowide='kubecolor get deployment --all-namespaces --watch -o=wide'
alias kgdepallwowidesl='kubecolor get deployment --all-namespaces --watch -o=wide --show-labels'
alias kgdepallwoyaml='kubecolor get deployment --all-namespaces --watch -o=yaml'
alias kgdepallwsl='kubecolor get deployment --all-namespaces --watch --show-labels'
alias kgdepallwslowide='kubecolor get deployment --all-namespaces --watch --show-labels -o=wide'
alias kgdepl='kubecolor get deployment -l'
alias kgdepn='kubecolor get deployment --namespace'
alias kgdepojson='kubecolor get deployment -o=json'
alias kgdepojsonall='kubecolor get deployment -o=json --all-namespaces'
alias kgdepojsonl='kubecolor get deployment -o=json -l'
alias kgdepojsonn='kubecolor get deployment -o=json --namespace'
alias kgdepowide='kubecolor get deployment -o=wide'
alias kgdepowideall='kubecolor get deployment -o=wide --all-namespaces'
alias kgdepowideallsl='kubecolor get deployment -o=wide --all-namespaces --show-labels'
alias kgdepowidel='kubecolor get deployment -o=wide -l'
alias kgdepowiden='kubecolor get deployment -o=wide --namespace'
alias kgdepowidesl='kubecolor get deployment -o=wide --show-labels'
alias kgdepowideslall='kubecolor get deployment -o=wide --show-labels --all-namespaces'
alias kgdepowidesll='kubecolor get deployment -o=wide --show-labels -l'
alias kgdepowidesln='kubecolor get deployment -o=wide --show-labels --namespace'
alias kgdepoyaml='kubecolor get deployment -o=yaml'
alias kgdepoyamlall='kubecolor get deployment -o=yaml --all-namespaces'
alias kgdepoyamll='kubecolor get deployment -o=yaml -l'
alias kgdepoyamln='kubecolor get deployment -o=yaml --namespace'
alias kgdepsl='kubecolor get deployment --show-labels'
alias kgdepslall='kubecolor get deployment --show-labels --all-namespaces'
alias kgdepslallowide='kubecolor get deployment --show-labels --all-namespaces -o=wide'
alias kgdepslallw='kubecolor get deployment --show-labels --all-namespaces --watch'
alias kgdepslallwowide='kubecolor get deployment --show-labels --all-namespaces --watch -o=wide'
alias kgdepsll='kubecolor get deployment --show-labels -l'
alias kgdepsln='kubecolor get deployment --show-labels --namespace'
alias kgdepslowide='kubecolor get deployment --show-labels -o=wide'
alias kgdepslowideall='kubecolor get deployment --show-labels -o=wide --all-namespaces'
alias kgdepslowidel='kubecolor get deployment --show-labels -o=wide -l'
alias kgdepslowiden='kubecolor get deployment --show-labels -o=wide --namespace'
alias kgdepslw='kubecolor get deployment --show-labels --watch'
alias kgdepslwall='kubecolor get deployment --show-labels --watch --all-namespaces'
alias kgdepslwallowide='kubecolor get deployment --show-labels --watch --all-namespaces -o=wide'
alias kgdepslwl='kubecolor get deployment --show-labels --watch -l'
alias kgdepslwn='kubecolor get deployment --show-labels --watch --namespace'
alias kgdepslwowide='kubecolor get deployment --show-labels --watch -o=wide'
alias kgdepslwowideall='kubecolor get deployment --show-labels --watch -o=wide --all-namespaces'
alias kgdepslwowidel='kubecolor get deployment --show-labels --watch -o=wide -l'
alias kgdepslwowiden='kubecolor get deployment --show-labels --watch -o=wide --namespace'
alias kgdepw='kubecolor get deployment --watch'
alias kgdepwall='kubecolor get deployment --watch --all-namespaces'
alias kgdepwallojson='kubecolor get deployment --watch --all-namespaces -o=json'
alias kgdepwallowide='kubecolor get deployment --watch --all-namespaces -o=wide'
alias kgdepwallowidesl='kubecolor get deployment --watch --all-namespaces -o=wide --show-labels'
alias kgdepwalloyaml='kubecolor get deployment --watch --all-namespaces -o=yaml'
alias kgdepwallsl='kubecolor get deployment --watch --all-namespaces --show-labels'
alias kgdepwallslowide='kubecolor get deployment --watch --all-namespaces --show-labels -o=wide'
alias kgdepwl='kubecolor get deployment --watch -l'
alias kgdepwn='kubecolor get deployment --watch --namespace'
alias kgdepwojson='kubecolor get deployment --watch -o=json'
alias kgdepwojsonall='kubecolor get deployment --watch -o=json --all-namespaces'
alias kgdepwojsonl='kubecolor get deployment --watch -o=json -l'
alias kgdepwojsonn='kubecolor get deployment --watch -o=json --namespace'
alias kgdepwowide='kubecolor get deployment --watch -o=wide'
alias kgdepwowideall='kubecolor get deployment --watch -o=wide --all-namespaces'
alias kgdepwowideallsl='kubecolor get deployment --watch -o=wide --all-namespaces --show-labels'
alias kgdepwowidel='kubecolor get deployment --watch -o=wide -l'
alias kgdepwowiden='kubecolor get deployment --watch -o=wide --namespace'
alias kgdepwowidesl='kubecolor get deployment --watch -o=wide --show-labels'
alias kgdepwowideslall='kubecolor get deployment --watch -o=wide --show-labels --all-namespaces'
alias kgdepwowidesll='kubecolor get deployment --watch -o=wide --show-labels -l'
alias kgdepwowidesln='kubecolor get deployment --watch -o=wide --show-labels --namespace'
alias kgdepwoyaml='kubecolor get deployment --watch -o=yaml'
alias kgdepwoyamlall='kubecolor get deployment --watch -o=yaml --all-namespaces'
alias kgdepwoyamll='kubecolor get deployment --watch -o=yaml -l'
alias kgdepwoyamln='kubecolor get deployment --watch -o=yaml --namespace'
alias kgdepwsl='kubecolor get deployment --watch --show-labels'
alias kgdepwslall='kubecolor get deployment --watch --show-labels --all-namespaces'
alias kgdepwslallowide='kubecolor get deployment --watch --show-labels --all-namespaces -o=wide'
alias kgdepwsll='kubecolor get deployment --watch --show-labels -l'
alias kgdepwsln='kubecolor get deployment --watch --show-labels --namespace'
alias kgdepwslowide='kubecolor get deployment --watch --show-labels -o=wide'
alias kgdepwslowideall='kubecolor get deployment --watch --show-labels -o=wide --all-namespaces'
alias kgdepwslowidel='kubecolor get deployment --watch --show-labels -o=wide -l'
alias kgdepwslowiden='kubecolor get deployment --watch --show-labels -o=wide --namespace'
alias kgf='kubecolor get --recursive -f'
alias kging='kubecolor get ingress'
alias kgingall='kubecolor get ingress --all-namespaces'
alias kgingallojson='kubecolor get ingress --all-namespaces -o=json'
alias kgingallowide='kubecolor get ingress --all-namespaces -o=wide'
alias kgingalloyaml='kubecolor get ingress --all-namespaces -o=yaml'
alias kgingallw='kubecolor get ingress --all-namespaces --watch'
alias kgingallwojson='kubecolor get ingress --all-namespaces --watch -o=json'
alias kgingallwowide='kubecolor get ingress --all-namespaces --watch -o=wide'
alias kgingallwoyaml='kubecolor get ingress --all-namespaces --watch -o=yaml'
alias kgingl='kubecolor get ingress -l'
alias kgingn='kubecolor get ingress --namespace'
alias kgingojson='kubecolor get ingress -o=json'
alias kgingojsonall='kubecolor get ingress -o=json --all-namespaces'
alias kgingojsonl='kubecolor get ingress -o=json -l'
alias kgingojsonn='kubecolor get ingress -o=json --namespace'
alias kgingowide='kubecolor get ingress -o=wide'
alias kgingowideall='kubecolor get ingress -o=wide --all-namespaces'
alias kgingowidel='kubecolor get ingress -o=wide -l'
alias kgingowiden='kubecolor get ingress -o=wide --namespace'
alias kgingoyaml='kubecolor get ingress -o=yaml'
alias kgingoyamlall='kubecolor get ingress -o=yaml --all-namespaces'
alias kgingoyamll='kubecolor get ingress -o=yaml -l'
alias kgingoyamln='kubecolor get ingress -o=yaml --namespace'
alias kgingw='kubecolor get ingress --watch'
alias kgingwall='kubecolor get ingress --watch --all-namespaces'
alias kgingwallojson='kubecolor get ingress --watch --all-namespaces -o=json'
alias kgingwallowide='kubecolor get ingress --watch --all-namespaces -o=wide'
alias kgingwalloyaml='kubecolor get ingress --watch --all-namespaces -o=yaml'
alias kgingwl='kubecolor get ingress --watch -l'
alias kgingwn='kubecolor get ingress --watch --namespace'
alias kgingwojson='kubecolor get ingress --watch -o=json'
alias kgingwojsonall='kubecolor get ingress --watch -o=json --all-namespaces'
alias kgingwojsonl='kubecolor get ingress --watch -o=json -l'
alias kgingwojsonn='kubecolor get ingress --watch -o=json --namespace'
alias kgingwowide='kubecolor get ingress --watch -o=wide'
alias kgingwowideall='kubecolor get ingress --watch -o=wide --all-namespaces'
alias kgingwowidel='kubecolor get ingress --watch -o=wide -l'
alias kgingwowiden='kubecolor get ingress --watch -o=wide --namespace'
alias kgingwoyaml='kubecolor get ingress --watch -o=yaml'
alias kgingwoyamlall='kubecolor get ingress --watch -o=yaml --all-namespaces'
alias kgingwoyamll='kubecolor get ingress --watch -o=yaml -l'
alias kgingwoyamln='kubecolor get ingress --watch -o=yaml --namespace'
alias kgl='kubecolor get -l'
alias kgn='kubecolor get --namespace'
alias kgno='kubecolor get nodes'
alias kgnol='kubecolor get nodes -l'
alias kgnoojson='kubecolor get nodes -o=json'
alias kgnoojsonl='kubecolor get nodes -o=json -l'
alias kgnoowide='kubecolor get nodes -o=wide'
alias kgnoowidel='kubecolor get nodes -o=wide -l'
alias kgnooyaml='kubecolor get nodes -o=yaml'
alias kgnooyamll='kubecolor get nodes -o=yaml -l'
alias kgnow='kubecolor get nodes --watch'
alias kgnowl='kubecolor get nodes --watch -l'
alias kgnowojson='kubecolor get nodes --watch -o=json'
alias kgnowojsonl='kubecolor get nodes --watch -o=json -l'
alias kgnowowide='kubecolor get nodes --watch -o=wide'
alias kgnowowidel='kubecolor get nodes --watch -o=wide -l'
alias kgnowoyaml='kubecolor get nodes --watch -o=yaml'
alias kgnowoyamll='kubecolor get nodes --watch -o=yaml -l'
alias kgns='kubecolor get namespaces'
alias kgnsall='kubecolor get namespaces --all-namespaces'
alias kgnsallojson='kubecolor get namespaces --all-namespaces -o=json'
alias kgnsallowide='kubecolor get namespaces --all-namespaces -o=wide'
alias kgnsalloyaml='kubecolor get namespaces --all-namespaces -o=yaml'
alias kgnsallw='kubecolor get namespaces --all-namespaces --watch'
alias kgnsallwojson='kubecolor get namespaces --all-namespaces --watch -o=json'
alias kgnsallwowide='kubecolor get namespaces --all-namespaces --watch -o=wide'
alias kgnsallwoyaml='kubecolor get namespaces --all-namespaces --watch -o=yaml'
alias kgnsl='kubecolor get namespaces -l'
alias kgnsojson='kubecolor get namespaces -o=json'
alias kgnsojsonall='kubecolor get namespaces -o=json --all-namespaces'
alias kgnsojsonl='kubecolor get namespaces -o=json -l'
alias kgnsowide='kubecolor get namespaces -o=wide'
alias kgnsowideall='kubecolor get namespaces -o=wide --all-namespaces'
alias kgnsowidel='kubecolor get namespaces -o=wide -l'
alias kgnsoyaml='kubecolor get namespaces -o=yaml'
alias kgnsoyamlall='kubecolor get namespaces -o=yaml --all-namespaces'
alias kgnsoyamll='kubecolor get namespaces -o=yaml -l'
alias kgnsw='kubecolor get namespaces --watch'
alias kgnswall='kubecolor get namespaces --watch --all-namespaces'
alias kgnswallojson='kubecolor get namespaces --watch --all-namespaces -o=json'
alias kgnswallowide='kubecolor get namespaces --watch --all-namespaces -o=wide'
alias kgnswalloyaml='kubecolor get namespaces --watch --all-namespaces -o=yaml'
alias kgnswl='kubecolor get namespaces --watch -l'
alias kgnswojson='kubecolor get namespaces --watch -o=json'
alias kgnswojsonall='kubecolor get namespaces --watch -o=json --all-namespaces'
alias kgnswojsonl='kubecolor get namespaces --watch -o=json -l'
alias kgnswowide='kubecolor get namespaces --watch -o=wide'
alias kgnswowideall='kubecolor get namespaces --watch -o=wide --all-namespaces'
alias kgnswowidel='kubecolor get namespaces --watch -o=wide -l'
alias kgnswoyaml='kubecolor get namespaces --watch -o=yaml'
alias kgnswoyamlall='kubecolor get namespaces --watch -o=yaml --all-namespaces'
alias kgnswoyamll='kubecolor get namespaces --watch -o=yaml -l'
alias kgojson='kubecolor get -o=json'
alias kgojsonall='kubecolor get -o=json --all-namespaces'
alias kgojsonf='kubecolor get -o=json --recursive -f'
alias kgojsonl='kubecolor get -o=json -l'
alias kgojsonn='kubecolor get -o=json --namespace'
alias kgowide='kubecolor get -o=wide'
alias kgowideall='kubecolor get -o=wide --all-namespaces'
alias kgowideallsl='kubecolor get -o=wide --all-namespaces --show-labels'
alias kgowidef='kubecolor get -o=wide --recursive -f'
alias kgowidel='kubecolor get -o=wide -l'
alias kgowiden='kubecolor get -o=wide --namespace'
alias kgowidesl='kubecolor get -o=wide --show-labels'
alias kgowideslall='kubecolor get -o=wide --show-labels --all-namespaces'
alias kgowideslf='kubecolor get -o=wide --show-labels --recursive -f'
alias kgowidesll='kubecolor get -o=wide --show-labels -l'
alias kgowidesln='kubecolor get -o=wide --show-labels --namespace'
alias kgoyaml='kubecolor get -o=yaml'
alias kgoyamlall='kubecolor get -o=yaml --all-namespaces'
alias kgoyamlf='kubecolor get -o=yaml --recursive -f'
alias kgoyamll='kubecolor get -o=yaml -l'
alias kgoyamln='kubecolor get -o=yaml --namespace'
alias kgpo='kubecolor get pods'
alias kgpoall='kubecolor get pods --all-namespaces'
alias kgpoallojson='kubecolor get pods --all-namespaces -o=json'
alias kgpoallowide='kubecolor get pods --all-namespaces -o=wide'
alias kgpoallowidesl='kubecolor get pods --all-namespaces -o=wide --show-labels'
alias kgpoalloyaml='kubecolor get pods --all-namespaces -o=yaml'
alias kgpoallsl='kubecolor get pods --all-namespaces --show-labels'
alias kgpoallslowide='kubecolor get pods --all-namespaces --show-labels -o=wide'
alias kgpoallslw='kubecolor get pods --all-namespaces --show-labels --watch'
alias kgpoallslwowide='kubecolor get pods --all-namespaces --show-labels --watch -o=wide'
alias kgpoallw='kubecolor get pods --all-namespaces --watch'
alias kgpoallwojson='kubecolor get pods --all-namespaces --watch -o=json'
alias kgpoallwowide='kubecolor get pods --all-namespaces --watch -o=wide'
alias kgpoallwowidesl='kubecolor get pods --all-namespaces --watch -o=wide --show-labels'
alias kgpoallwoyaml='kubecolor get pods --all-namespaces --watch -o=yaml'
alias kgpoallwsl='kubecolor get pods --all-namespaces --watch --show-labels'
alias kgpoallwslowide='kubecolor get pods --all-namespaces --watch --show-labels -o=wide'
alias kgpol='kubecolor get pods -l'
alias kgpon='kubecolor get pods --namespace'
alias kgpoojson='kubecolor get pods -o=json'
alias kgpoojsonall='kubecolor get pods -o=json --all-namespaces'
alias kgpoojsonl='kubecolor get pods -o=json -l'
alias kgpoojsonn='kubecolor get pods -o=json --namespace'
alias kgpoowide='kubecolor get pods -o=wide'
alias kgpoowideall='kubecolor get pods -o=wide --all-namespaces'
alias kgpoowideallsl='kubecolor get pods -o=wide --all-namespaces --show-labels'
alias kgpoowidel='kubecolor get pods -o=wide -l'
alias kgpoowiden='kubecolor get pods -o=wide --namespace'
alias kgpoowidesl='kubecolor get pods -o=wide --show-labels'
alias kgpoowideslall='kubecolor get pods -o=wide --show-labels --all-namespaces'
alias kgpoowidesll='kubecolor get pods -o=wide --show-labels -l'
alias kgpoowidesln='kubecolor get pods -o=wide --show-labels --namespace'
alias kgpooyaml='kubecolor get pods -o=yaml'
alias kgpooyamlall='kubecolor get pods -o=yaml --all-namespaces'
alias kgpooyamll='kubecolor get pods -o=yaml -l'
alias kgpooyamln='kubecolor get pods -o=yaml --namespace'
alias kgposl='kubecolor get pods --show-labels'
alias kgposlall='kubecolor get pods --show-labels --all-namespaces'
alias kgposlallowide='kubecolor get pods --show-labels --all-namespaces -o=wide'
alias kgposlallw='kubecolor get pods --show-labels --all-namespaces --watch'
alias kgposlallwowide='kubecolor get pods --show-labels --all-namespaces --watch -o=wide'
alias kgposll='kubecolor get pods --show-labels -l'
alias kgposln='kubecolor get pods --show-labels --namespace'
alias kgposlowide='kubecolor get pods --show-labels -o=wide'
alias kgposlowideall='kubecolor get pods --show-labels -o=wide --all-namespaces'
alias kgposlowidel='kubecolor get pods --show-labels -o=wide -l'
alias kgposlowiden='kubecolor get pods --show-labels -o=wide --namespace'
alias kgposlw='kubecolor get pods --show-labels --watch'
alias kgposlwall='kubecolor get pods --show-labels --watch --all-namespaces'
alias kgposlwallowide='kubecolor get pods --show-labels --watch --all-namespaces -o=wide'
alias kgposlwl='kubecolor get pods --show-labels --watch -l'
alias kgposlwn='kubecolor get pods --show-labels --watch --namespace'
alias kgposlwowide='kubecolor get pods --show-labels --watch -o=wide'
alias kgposlwowideall='kubecolor get pods --show-labels --watch -o=wide --all-namespaces'
alias kgposlwowidel='kubecolor get pods --show-labels --watch -o=wide -l'
alias kgposlwowiden='kubecolor get pods --show-labels --watch -o=wide --namespace'
alias kgpow='kubecolor get pods --watch'
alias kgpowall='kubecolor get pods --watch --all-namespaces'
alias kgpowallojson='kubecolor get pods --watch --all-namespaces -o=json'
alias kgpowallowide='kubecolor get pods --watch --all-namespaces -o=wide'
alias kgpowallowidesl='kubecolor get pods --watch --all-namespaces -o=wide --show-labels'
alias kgpowalloyaml='kubecolor get pods --watch --all-namespaces -o=yaml'
alias kgpowallsl='kubecolor get pods --watch --all-namespaces --show-labels'
alias kgpowallslowide='kubecolor get pods --watch --all-namespaces --show-labels -o=wide'
alias kgpowl='kubecolor get pods --watch -l'
alias kgpown='kubecolor get pods --watch --namespace'
alias kgpowojson='kubecolor get pods --watch -o=json'
alias kgpowojsonall='kubecolor get pods --watch -o=json --all-namespaces'
alias kgpowojsonl='kubecolor get pods --watch -o=json -l'
alias kgpowojsonn='kubecolor get pods --watch -o=json --namespace'
alias kgpowowide='kubecolor get pods --watch -o=wide'
alias kgpowowideall='kubecolor get pods --watch -o=wide --all-namespaces'
alias kgpowowideallsl='kubecolor get pods --watch -o=wide --all-namespaces --show-labels'
alias kgpowowidel='kubecolor get pods --watch -o=wide -l'
alias kgpowowiden='kubecolor get pods --watch -o=wide --namespace'
alias kgpowowidesl='kubecolor get pods --watch -o=wide --show-labels'
alias kgpowowideslall='kubecolor get pods --watch -o=wide --show-labels --all-namespaces'
alias kgpowowidesll='kubecolor get pods --watch -o=wide --show-labels -l'
alias kgpowowidesln='kubecolor get pods --watch -o=wide --show-labels --namespace'
alias kgpowoyaml='kubecolor get pods --watch -o=yaml'
alias kgpowoyamlall='kubecolor get pods --watch -o=yaml --all-namespaces'
alias kgpowoyamll='kubecolor get pods --watch -o=yaml -l'
alias kgpowoyamln='kubecolor get pods --watch -o=yaml --namespace'
alias kgpowsl='kubecolor get pods --watch --show-labels'
alias kgpowslall='kubecolor get pods --watch --show-labels --all-namespaces'
alias kgpowslallowide='kubecolor get pods --watch --show-labels --all-namespaces -o=wide'
alias kgpowsll='kubecolor get pods --watch --show-labels -l'
alias kgpowsln='kubecolor get pods --watch --show-labels --namespace'
alias kgpowslowide='kubecolor get pods --watch --show-labels -o=wide'
alias kgpowslowideall='kubecolor get pods --watch --show-labels -o=wide --all-namespaces'
alias kgpowslowidel='kubecolor get pods --watch --show-labels -o=wide -l'
alias kgpowslowiden='kubecolor get pods --watch --show-labels -o=wide --namespace'
alias kgsec='kubecolor get secret'
alias kgsecall='kubecolor get secret --all-namespaces'
alias kgsecallojson='kubecolor get secret --all-namespaces -o=json'
alias kgsecallowide='kubecolor get secret --all-namespaces -o=wide'
alias kgsecalloyaml='kubecolor get secret --all-namespaces -o=yaml'
alias kgsecallw='kubecolor get secret --all-namespaces --watch'
alias kgsecallwojson='kubecolor get secret --all-namespaces --watch -o=json'
alias kgsecallwowide='kubecolor get secret --all-namespaces --watch -o=wide'
alias kgsecallwoyaml='kubecolor get secret --all-namespaces --watch -o=yaml'
alias kgsecl='kubecolor get secret -l'
alias kgsecn='kubecolor get secret --namespace'
alias kgsecojson='kubecolor get secret -o=json'
alias kgsecojsonall='kubecolor get secret -o=json --all-namespaces'
alias kgsecojsonl='kubecolor get secret -o=json -l'
alias kgsecojsonn='kubecolor get secret -o=json --namespace'
alias kgsecowide='kubecolor get secret -o=wide'
alias kgsecowideall='kubecolor get secret -o=wide --all-namespaces'
alias kgsecowidel='kubecolor get secret -o=wide -l'
alias kgsecowiden='kubecolor get secret -o=wide --namespace'
alias kgsecoyaml='kubecolor get secret -o=yaml'
alias kgsecoyamlall='kubecolor get secret -o=yaml --all-namespaces'
alias kgsecoyamll='kubecolor get secret -o=yaml -l'
alias kgsecoyamln='kubecolor get secret -o=yaml --namespace'
alias kgsecw='kubecolor get secret --watch'
alias kgsecwall='kubecolor get secret --watch --all-namespaces'
alias kgsecwallojson='kubecolor get secret --watch --all-namespaces -o=json'
alias kgsecwallowide='kubecolor get secret --watch --all-namespaces -o=wide'
alias kgsecwalloyaml='kubecolor get secret --watch --all-namespaces -o=yaml'
alias kgsecwl='kubecolor get secret --watch -l'
alias kgsecwn='kubecolor get secret --watch --namespace'
alias kgsecwojson='kubecolor get secret --watch -o=json'
alias kgsecwojsonall='kubecolor get secret --watch -o=json --all-namespaces'
alias kgsecwojsonl='kubecolor get secret --watch -o=json -l'
alias kgsecwojsonn='kubecolor get secret --watch -o=json --namespace'
alias kgsecwowide='kubecolor get secret --watch -o=wide'
alias kgsecwowideall='kubecolor get secret --watch -o=wide --all-namespaces'
alias kgsecwowidel='kubecolor get secret --watch -o=wide -l'
alias kgsecwowiden='kubecolor get secret --watch -o=wide --namespace'
alias kgsecwoyaml='kubecolor get secret --watch -o=yaml'
alias kgsecwoyamlall='kubecolor get secret --watch -o=yaml --all-namespaces'
alias kgsecwoyamll='kubecolor get secret --watch -o=yaml -l'
alias kgsecwoyamln='kubecolor get secret --watch -o=yaml --namespace'
alias kgsl='kubecolor get --show-labels'
alias kgslall='kubecolor get --show-labels --all-namespaces'
alias kgslallowide='kubecolor get --show-labels --all-namespaces -o=wide'
alias kgslallw='kubecolor get --show-labels --all-namespaces --watch'
alias kgslallwowide='kubecolor get --show-labels --all-namespaces --watch -o=wide'
alias kgslf='kubecolor get --show-labels --recursive -f'
alias kgsll='kubecolor get --show-labels -l'
alias kgsln='kubecolor get --show-labels --namespace'
alias kgslowide='kubecolor get --show-labels -o=wide'
alias kgslowideall='kubecolor get --show-labels -o=wide --all-namespaces'
alias kgslowidef='kubecolor get --show-labels -o=wide --recursive -f'
alias kgslowidel='kubecolor get --show-labels -o=wide -l'
alias kgslowiden='kubecolor get --show-labels -o=wide --namespace'
alias kgslw='kubecolor get --show-labels --watch'
alias kgslwall='kubecolor get --show-labels --watch --all-namespaces'
alias kgslwallowide='kubecolor get --show-labels --watch --all-namespaces -o=wide'
alias kgslwf='kubecolor get --show-labels --watch --recursive -f'
alias kgslwl='kubecolor get --show-labels --watch -l'
alias kgslwn='kubecolor get --show-labels --watch --namespace'
alias kgslwowide='kubecolor get --show-labels --watch -o=wide'
alias kgslwowideall='kubecolor get --show-labels --watch -o=wide --all-namespaces'
alias kgslwowidef='kubecolor get --show-labels --watch -o=wide --recursive -f'
alias kgslwowidel='kubecolor get --show-labels --watch -o=wide -l'
alias kgslwowiden='kubecolor get --show-labels --watch -o=wide --namespace'
alias kgsvc='kubecolor get service'
alias kgsvcall='kubecolor get service --all-namespaces'
alias kgsvcallojson='kubecolor get service --all-namespaces -o=json'
alias kgsvcallowide='kubecolor get service --all-namespaces -o=wide'
alias kgsvcalloyaml='kubecolor get service --all-namespaces -o=yaml'
alias kgsvcallw='kubecolor get service --all-namespaces --watch'
alias kgsvcallwojson='kubecolor get service --all-namespaces --watch -o=json'
alias kgsvcallwowide='kubecolor get service --all-namespaces --watch -o=wide'
alias kgsvcallwoyaml='kubecolor get service --all-namespaces --watch -o=yaml'
alias kgsvcl='kubecolor get service -l'
alias kgsvcn='kubecolor get service --namespace'
alias kgsvcojson='kubecolor get service -o=json'
alias kgsvcojsonall='kubecolor get service -o=json --all-namespaces'
alias kgsvcojsonl='kubecolor get service -o=json -l'
alias kgsvcojsonn='kubecolor get service -o=json --namespace'
alias kgsvcowide='kubecolor get service -o=wide'
alias kgsvcowideall='kubecolor get service -o=wide --all-namespaces'
alias kgsvcowidel='kubecolor get service -o=wide -l'
alias kgsvcowiden='kubecolor get service -o=wide --namespace'
alias kgsvcoyaml='kubecolor get service -o=yaml'
alias kgsvcoyamlall='kubecolor get service -o=yaml --all-namespaces'
alias kgsvcoyamll='kubecolor get service -o=yaml -l'
alias kgsvcoyamln='kubecolor get service -o=yaml --namespace'
alias kgsvcw='kubecolor get service --watch'
alias kgsvcwall='kubecolor get service --watch --all-namespaces'
alias kgsvcwallojson='kubecolor get service --watch --all-namespaces -o=json'
alias kgsvcwallowide='kubecolor get service --watch --all-namespaces -o=wide'
alias kgsvcwalloyaml='kubecolor get service --watch --all-namespaces -o=yaml'
alias kgsvcwl='kubecolor get service --watch -l'
alias kgsvcwn='kubecolor get service --watch --namespace'
alias kgsvcwojson='kubecolor get service --watch -o=json'
alias kgsvcwojsonall='kubecolor get service --watch -o=json --all-namespaces'
alias kgsvcwojsonl='kubecolor get service --watch -o=json -l'
alias kgsvcwojsonn='kubecolor get service --watch -o=json --namespace'
alias kgsvcwowide='kubecolor get service --watch -o=wide'
alias kgsvcwowideall='kubecolor get service --watch -o=wide --all-namespaces'
alias kgsvcwowidel='kubecolor get service --watch -o=wide -l'
alias kgsvcwowiden='kubecolor get service --watch -o=wide --namespace'
alias kgsvcwoyaml='kubecolor get service --watch -o=yaml'
alias kgsvcwoyamlall='kubecolor get service --watch -o=yaml --all-namespaces'
alias kgsvcwoyamll='kubecolor get service --watch -o=yaml -l'
alias kgsvcwoyamln='kubecolor get service --watch -o=yaml --namespace'
alias kgu='kubectl config use-context'
alias kgw='kubecolor get --watch'
alias kgwall='kubecolor get --watch --all-namespaces'
alias kgwallojson='kubecolor get --watch --all-namespaces -o=json'
alias kgwallowide='kubecolor get --watch --all-namespaces -o=wide'
alias kgwallowidesl='kubecolor get --watch --all-namespaces -o=wide --show-labels'
alias kgwalloyaml='kubecolor get --watch --all-namespaces -o=yaml'
alias kgwallsl='kubecolor get --watch --all-namespaces --show-labels'
alias kgwallslowide='kubecolor get --watch --all-namespaces --show-labels -o=wide'
alias kgwf='kubecolor get --watch --recursive -f'
alias kgwl='kubecolor get --watch -l'
alias kgwn='kubecolor get --watch --namespace'
alias kgwojson='kubecolor get --watch -o=json'
alias kgwojsonall='kubecolor get --watch -o=json --all-namespaces'
alias kgwojsonf='kubecolor get --watch -o=json --recursive -f'
alias kgwojsonl='kubecolor get --watch -o=json -l'
alias kgwojsonn='kubecolor get --watch -o=json --namespace'
alias kgwowide='kubecolor get --watch -o=wide'
alias kgwowideall='kubecolor get --watch -o=wide --all-namespaces'
alias kgwowideallsl='kubecolor get --watch -o=wide --all-namespaces --show-labels'
alias kgwowidef='kubecolor get --watch -o=wide --recursive -f'
alias kgwowidel='kubecolor get --watch -o=wide -l'
alias kgwowiden='kubecolor get --watch -o=wide --namespace'
alias kgwowidesl='kubecolor get --watch -o=wide --show-labels'
alias kgwowideslall='kubecolor get --watch -o=wide --show-labels --all-namespaces'
alias kgwowideslf='kubecolor get --watch -o=wide --show-labels --recursive -f'
alias kgwowidesll='kubecolor get --watch -o=wide --show-labels -l'
alias kgwowidesln='kubecolor get --watch -o=wide --show-labels --namespace'
alias kgwoyaml='kubecolor get --watch -o=yaml'
alias kgwoyamlall='kubecolor get --watch -o=yaml --all-namespaces'
alias kgwoyamlf='kubecolor get --watch -o=yaml --recursive -f'
alias kgwoyamll='kubecolor get --watch -o=yaml -l'
alias kgwoyamln='kubecolor get --watch -o=yaml --namespace'
alias kgwsl='kubecolor get --watch --show-labels'
alias kgwslall='kubecolor get --watch --show-labels --all-namespaces'
alias kgwslallowide='kubecolor get --watch --show-labels --all-namespaces -o=wide'
alias kgwslf='kubecolor get --watch --show-labels --recursive -f'
alias kgwsll='kubecolor get --watch --show-labels -l'
alias kgwsln='kubecolor get --watch --show-labels --namespace'
alias kgwslowide='kubecolor get --watch --show-labels -o=wide'
alias kgwslowideall='kubecolor get --watch --show-labels -o=wide --all-namespaces'
alias kgwslowidef='kubecolor get --watch --show-labels -o=wide --recursive -f'
alias kgwslowidel='kubecolor get --watch --show-labels -o=wide -l'
alias kgwslowiden='kubecolor get --watch --show-labels -o=wide --namespace'
alias klo='kubectl logs -f'
alias klon='kubectl logs -f --namespace'
alias klot='kubectl logs -f --tail=100'
alias klotn='kubectl logs -f --tail=100 --namespace'
alias kp='kubecolor proxy'
alias kpf='kubecolor port-forward'
alias krm='kubecolor delete'
alias krmall='kubecolor delete --all'
alias krmcm='kubecolor delete configmap'
alias krmcmall='kubecolor delete configmap --all'
alias krmcml='kubecolor delete configmap -l'
alias krmcmn='kubecolor delete configmap --namespace'
alias krmdep='kubecolor delete deployment'
alias krmdepall='kubecolor delete deployment --all'
alias krmdepl='kubecolor delete deployment -l'
alias krmdepn='kubecolor delete deployment --namespace'
alias krmf='kubecolor delete --recursive -f'
alias krming='kubecolor delete ingress'
alias krmingall='kubecolor delete ingress --all'
alias krmingl='kubecolor delete ingress -l'
alias krmingn='kubecolor delete ingress --namespace'
alias krml='kubecolor delete -l'
alias krmn='kubecolor delete --namespace'
alias krmns='kubecolor delete namespaces'
alias krmnsall='kubecolor delete namespaces --all'
alias krmnsl='kubecolor delete namespaces -l'
alias krmpo='kubecolor delete pods'
alias krmpoall='kubecolor delete pods --all'
alias krmpol='kubecolor delete pods -l'
alias krmpon='kubecolor delete pods --namespace'
alias krmsec='kubecolor delete secret'
alias krmsecall='kubecolor delete secret --all'
alias krmsecl='kubecolor delete secret -l'
alias krmsecn='kubecolor delete secret --namespace'
alias krmsvc='kubecolor delete service'
alias krmsvcall='kubecolor delete service --all'
alias krmsvcl='kubecolor delete service -l'
alias krmsvcn='kubecolor delete service --namespace'
alias krun='kubecolor run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksys='kubecolor --namespace=kube-system'
alias ksysa='kubecolor --namespace=kube-system apply --recursive -f'
alias ksysd='kubecolor --namespace=kube-system describe'
alias ksysdcm='kubecolor --namespace=kube-system describe configmap'
alias ksysdcml='kubecolor --namespace=kube-system describe configmap -l'
alias ksysddep='kubecolor --namespace=kube-system describe deployment'
alias ksysddepl='kubecolor --namespace=kube-system describe deployment -l'
alias ksysding='kubecolor --namespace=kube-system describe ingress'
alias ksysdingl='kubecolor --namespace=kube-system describe ingress -l'
alias ksysdl='kubecolor --namespace=kube-system describe -l'
alias ksysdpo='kubecolor --namespace=kube-system describe pods'
alias ksysdpol='kubecolor --namespace=kube-system describe pods -l'
alias ksysdsec='kubecolor --namespace=kube-system describe secret'
alias ksysdsecl='kubecolor --namespace=kube-system describe secret -l'
alias ksysdsvc='kubecolor --namespace=kube-system describe service'
alias ksysdsvcl='kubecolor --namespace=kube-system describe service -l'
alias ksysex='kubecolor --namespace=kube-system exec -i -t'
alias ksysg='kubecolor --namespace=kube-system get'
alias ksysgcm='kubecolor --namespace=kube-system get configmap'
alias ksysgcml='kubecolor --namespace=kube-system get configmap -l'
alias ksysgcmojson='kubecolor --namespace=kube-system get configmap -o=json'
alias ksysgcmojsonl='kubecolor --namespace=kube-system get configmap -o=json -l'
alias ksysgcmowide='kubecolor --namespace=kube-system get configmap -o=wide'
alias ksysgcmowidel='kubecolor --namespace=kube-system get configmap -o=wide -l'
alias ksysgcmoyaml='kubecolor --namespace=kube-system get configmap -o=yaml'
alias ksysgcmoyamll='kubecolor --namespace=kube-system get configmap -o=yaml -l'
alias ksysgcmw='kubecolor --namespace=kube-system get configmap --watch'
alias ksysgcmwl='kubecolor --namespace=kube-system get configmap --watch -l'
alias ksysgcmwojson='kubecolor --namespace=kube-system get configmap --watch -o=json'
alias ksysgcmwojsonl='kubecolor --namespace=kube-system get configmap --watch -o=json -l'
alias ksysgcmwowide='kubecolor --namespace=kube-system get configmap --watch -o=wide'
alias ksysgcmwowidel='kubecolor --namespace=kube-system get configmap --watch -o=wide -l'
alias ksysgcmwoyaml='kubecolor --namespace=kube-system get configmap --watch -o=yaml'
alias ksysgcmwoyamll='kubecolor --namespace=kube-system get configmap --watch -o=yaml -l'
alias ksysgdep='kubecolor --namespace=kube-system get deployment'
alias ksysgdepl='kubecolor --namespace=kube-system get deployment -l'
alias ksysgdepojson='kubecolor --namespace=kube-system get deployment -o=json'
alias ksysgdepojsonl='kubecolor --namespace=kube-system get deployment -o=json -l'
alias ksysgdepowide='kubecolor --namespace=kube-system get deployment -o=wide'
alias ksysgdepowidel='kubecolor --namespace=kube-system get deployment -o=wide -l'
alias ksysgdepowidesl='kubecolor --namespace=kube-system get deployment -o=wide --show-labels'
alias ksysgdepowidesll='kubecolor --namespace=kube-system get deployment -o=wide --show-labels -l'
alias ksysgdepoyaml='kubecolor --namespace=kube-system get deployment -o=yaml'
alias ksysgdepoyamll='kubecolor --namespace=kube-system get deployment -o=yaml -l'
alias ksysgdepsl='kubecolor --namespace=kube-system get deployment --show-labels'
alias ksysgdepsll='kubecolor --namespace=kube-system get deployment --show-labels -l'
alias ksysgdepslowide='kubecolor --namespace=kube-system get deployment --show-labels -o=wide'
alias ksysgdepslowidel='kubecolor --namespace=kube-system get deployment --show-labels -o=wide -l'
alias ksysgdepslw='kubecolor --namespace=kube-system get deployment --show-labels --watch'
alias ksysgdepslwl='kubecolor --namespace=kube-system get deployment --show-labels --watch -l'
alias ksysgdepslwowide='kubecolor --namespace=kube-system get deployment --show-labels --watch -o=wide'
alias ksysgdepslwowidel='kubecolor --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
alias ksysgdepw='kubecolor --namespace=kube-system get deployment --watch'
alias ksysgdepwl='kubecolor --namespace=kube-system get deployment --watch -l'
alias ksysgdepwojson='kubecolor --namespace=kube-system get deployment --watch -o=json'
alias ksysgdepwojsonl='kubecolor --namespace=kube-system get deployment --watch -o=json -l'
alias ksysgdepwowide='kubecolor --namespace=kube-system get deployment --watch -o=wide'
alias ksysgdepwowidel='kubecolor --namespace=kube-system get deployment --watch -o=wide -l'
alias ksysgdepwowidesl='kubecolor --namespace=kube-system get deployment --watch -o=wide --show-labels'
alias ksysgdepwowidesll='kubecolor --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
alias ksysgdepwoyaml='kubecolor --namespace=kube-system get deployment --watch -o=yaml'
alias ksysgdepwoyamll='kubecolor --namespace=kube-system get deployment --watch -o=yaml -l'
alias ksysgdepwsl='kubecolor --namespace=kube-system get deployment --watch --show-labels'
alias ksysgdepwsll='kubecolor --namespace=kube-system get deployment --watch --show-labels -l'
alias ksysgdepwslowide='kubecolor --namespace=kube-system get deployment --watch --show-labels -o=wide'
alias ksysgdepwslowidel='kubecolor --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
alias ksysging='kubecolor --namespace=kube-system get ingress'
alias ksysgingl='kubecolor --namespace=kube-system get ingress -l'
alias ksysgingojson='kubecolor --namespace=kube-system get ingress -o=json'
alias ksysgingojsonl='kubecolor --namespace=kube-system get ingress -o=json -l'
alias ksysgingowide='kubecolor --namespace=kube-system get ingress -o=wide'
alias ksysgingowidel='kubecolor --namespace=kube-system get ingress -o=wide -l'
alias ksysgingoyaml='kubecolor --namespace=kube-system get ingress -o=yaml'
alias ksysgingoyamll='kubecolor --namespace=kube-system get ingress -o=yaml -l'
alias ksysgingw='kubecolor --namespace=kube-system get ingress --watch'
alias ksysgingwl='kubecolor --namespace=kube-system get ingress --watch -l'
alias ksysgingwojson='kubecolor --namespace=kube-system get ingress --watch -o=json'
alias ksysgingwojsonl='kubecolor --namespace=kube-system get ingress --watch -o=json -l'
alias ksysgingwowide='kubecolor --namespace=kube-system get ingress --watch -o=wide'
alias ksysgingwowidel='kubecolor --namespace=kube-system get ingress --watch -o=wide -l'
alias ksysgingwoyaml='kubecolor --namespace=kube-system get ingress --watch -o=yaml'
alias ksysgingwoyamll='kubecolor --namespace=kube-system get ingress --watch -o=yaml -l'
alias ksysgl='kubecolor --namespace=kube-system get -l'
alias ksysgojson='kubecolor --namespace=kube-system get -o=json'
alias ksysgojsonl='kubecolor --namespace=kube-system get -o=json -l'
alias ksysgowide='kubecolor --namespace=kube-system get -o=wide'
alias ksysgowidel='kubecolor --namespace=kube-system get -o=wide -l'
alias ksysgowidesl='kubecolor --namespace=kube-system get -o=wide --show-labels'
alias ksysgowidesll='kubecolor --namespace=kube-system get -o=wide --show-labels -l'
alias ksysgoyaml='kubecolor --namespace=kube-system get -o=yaml'
alias ksysgoyamll='kubecolor --namespace=kube-system get -o=yaml -l'
alias ksysgpo='kubecolor --namespace=kube-system get pods'
alias ksysgpol='kubecolor --namespace=kube-system get pods -l'
alias ksysgpoojson='kubecolor --namespace=kube-system get pods -o=json'
alias ksysgpoojsonl='kubecolor --namespace=kube-system get pods -o=json -l'
alias ksysgpoowide='kubecolor --namespace=kube-system get pods -o=wide'
alias ksysgpoowidel='kubecolor --namespace=kube-system get pods -o=wide -l'
alias ksysgpoowidesl='kubecolor --namespace=kube-system get pods -o=wide --show-labels'
alias ksysgpoowidesll='kubecolor --namespace=kube-system get pods -o=wide --show-labels -l'
alias ksysgpooyaml='kubecolor --namespace=kube-system get pods -o=yaml'
alias ksysgpooyamll='kubecolor --namespace=kube-system get pods -o=yaml -l'
alias ksysgposl='kubecolor --namespace=kube-system get pods --show-labels'
alias ksysgposll='kubecolor --namespace=kube-system get pods --show-labels -l'
alias ksysgposlowide='kubecolor --namespace=kube-system get pods --show-labels -o=wide'
alias ksysgposlowidel='kubecolor --namespace=kube-system get pods --show-labels -o=wide -l'
alias ksysgposlw='kubecolor --namespace=kube-system get pods --show-labels --watch'
alias ksysgposlwl='kubecolor --namespace=kube-system get pods --show-labels --watch -l'
alias ksysgposlwowide='kubecolor --namespace=kube-system get pods --show-labels --watch -o=wide'
alias ksysgposlwowidel='kubecolor --namespace=kube-system get pods --show-labels --watch -o=wide -l'
alias ksysgpow='kubecolor --namespace=kube-system get pods --watch'
alias ksysgpowl='kubecolor --namespace=kube-system get pods --watch -l'
alias ksysgpowojson='kubecolor --namespace=kube-system get pods --watch -o=json'
alias ksysgpowojsonl='kubecolor --namespace=kube-system get pods --watch -o=json -l'
alias ksysgpowowide='kubecolor --namespace=kube-system get pods --watch -o=wide'
alias ksysgpowowidel='kubecolor --namespace=kube-system get pods --watch -o=wide -l'
alias ksysgpowowidesl='kubecolor --namespace=kube-system get pods --watch -o=wide --show-labels'
alias ksysgpowowidesll='kubecolor --namespace=kube-system get pods --watch -o=wide --show-labels -l'
alias ksysgpowoyaml='kubecolor --namespace=kube-system get pods --watch -o=yaml'
alias ksysgpowoyamll='kubecolor --namespace=kube-system get pods --watch -o=yaml -l'
alias ksysgpowsl='kubecolor --namespace=kube-system get pods --watch --show-labels'
alias ksysgpowsll='kubecolor --namespace=kube-system get pods --watch --show-labels -l'
alias ksysgpowslowide='kubecolor --namespace=kube-system get pods --watch --show-labels -o=wide'
alias ksysgpowslowidel='kubecolor --namespace=kube-system get pods --watch --show-labels -o=wide -l'
alias ksysgsec='kubecolor --namespace=kube-system get secret'
alias ksysgsecl='kubecolor --namespace=kube-system get secret -l'
alias ksysgsecojson='kubecolor --namespace=kube-system get secret -o=json'
alias ksysgsecojsonl='kubecolor --namespace=kube-system get secret -o=json -l'
alias ksysgsecowide='kubecolor --namespace=kube-system get secret -o=wide'
alias ksysgsecowidel='kubecolor --namespace=kube-system get secret -o=wide -l'
alias ksysgsecoyaml='kubecolor --namespace=kube-system get secret -o=yaml'
alias ksysgsecoyamll='kubecolor --namespace=kube-system get secret -o=yaml -l'
alias ksysgsecw='kubecolor --namespace=kube-system get secret --watch'
alias ksysgsecwl='kubecolor --namespace=kube-system get secret --watch -l'
alias ksysgsecwojson='kubecolor --namespace=kube-system get secret --watch -o=json'
alias ksysgsecwojsonl='kubecolor --namespace=kube-system get secret --watch -o=json -l'
alias ksysgsecwowide='kubecolor --namespace=kube-system get secret --watch -o=wide'
alias ksysgsecwowidel='kubecolor --namespace=kube-system get secret --watch -o=wide -l'
alias ksysgsecwoyaml='kubecolor --namespace=kube-system get secret --watch -o=yaml'
alias ksysgsecwoyamll='kubecolor --namespace=kube-system get secret --watch -o=yaml -l'
alias ksysgsl='kubecolor --namespace=kube-system get --show-labels'
alias ksysgsll='kubecolor --namespace=kube-system get --show-labels -l'
alias ksysgslowide='kubecolor --namespace=kube-system get --show-labels -o=wide'
alias ksysgslowidel='kubecolor --namespace=kube-system get --show-labels -o=wide -l'
alias ksysgslw='kubecolor --namespace=kube-system get --show-labels --watch'
alias ksysgslwl='kubecolor --namespace=kube-system get --show-labels --watch -l'
alias ksysgslwowide='kubecolor --namespace=kube-system get --show-labels --watch -o=wide'
alias ksysgslwowidel='kubecolor --namespace=kube-system get --show-labels --watch -o=wide -l'
alias ksysgsvc='kubecolor --namespace=kube-system get service'
alias ksysgsvcl='kubecolor --namespace=kube-system get service -l'
alias ksysgsvcojson='kubecolor --namespace=kube-system get service -o=json'
alias ksysgsvcojsonl='kubecolor --namespace=kube-system get service -o=json -l'
alias ksysgsvcowide='kubecolor --namespace=kube-system get service -o=wide'
alias ksysgsvcowidel='kubecolor --namespace=kube-system get service -o=wide -l'
alias ksysgsvcoyaml='kubecolor --namespace=kube-system get service -o=yaml'
alias ksysgsvcoyamll='kubecolor --namespace=kube-system get service -o=yaml -l'
alias ksysgsvcw='kubecolor --namespace=kube-system get service --watch'
alias ksysgsvcwl='kubecolor --namespace=kube-system get service --watch -l'
alias ksysgsvcwojson='kubecolor --namespace=kube-system get service --watch -o=json'
alias ksysgsvcwojsonl='kubecolor --namespace=kube-system get service --watch -o=json -l'
alias ksysgsvcwowide='kubecolor --namespace=kube-system get service --watch -o=wide'
alias ksysgsvcwowidel='kubecolor --namespace=kube-system get service --watch -o=wide -l'
alias ksysgsvcwoyaml='kubecolor --namespace=kube-system get service --watch -o=yaml'
alias ksysgsvcwoyamll='kubecolor --namespace=kube-system get service --watch -o=yaml -l'
alias ksysgw='kubecolor --namespace=kube-system get --watch'
alias ksysgwl='kubecolor --namespace=kube-system get --watch -l'
alias ksysgwojson='kubecolor --namespace=kube-system get --watch -o=json'
alias ksysgwojsonl='kubecolor --namespace=kube-system get --watch -o=json -l'
alias ksysgwowide='kubecolor --namespace=kube-system get --watch -o=wide'
alias ksysgwowidel='kubecolor --namespace=kube-system get --watch -o=wide -l'
alias ksysgwowidesl='kubecolor --namespace=kube-system get --watch -o=wide --show-labels'
alias ksysgwowidesll='kubecolor --namespace=kube-system get --watch -o=wide --show-labels -l'
alias ksysgwoyaml='kubecolor --namespace=kube-system get --watch -o=yaml'
alias ksysgwoyamll='kubecolor --namespace=kube-system get --watch -o=yaml -l'
alias ksysgwsl='kubecolor --namespace=kube-system get --watch --show-labels'
alias ksysgwsll='kubecolor --namespace=kube-system get --watch --show-labels -l'
alias ksysgwslowide='kubecolor --namespace=kube-system get --watch --show-labels -o=wide'
alias ksysgwslowidel='kubecolor --namespace=kube-system get --watch --show-labels -o=wide -l'
alias ksyslo='kubecolor --namespace=kube-system logs -f'
alias ksyslot='kubecolor --namespace=kube-system logs -f --tail=100'
alias ksysrm='kubecolor --namespace=kube-system delete'
alias ksysrmall='kubecolor --namespace=kube-system delete --all'
alias ksysrmcm='kubecolor --namespace=kube-system delete configmap'
alias ksysrmcmall='kubecolor --namespace=kube-system delete configmap --all'
alias ksysrmcml='kubecolor --namespace=kube-system delete configmap -l'
alias ksysrmdep='kubecolor --namespace=kube-system delete deployment'
alias ksysrmdepall='kubecolor --namespace=kube-system delete deployment --all'
alias ksysrmdepl='kubecolor --namespace=kube-system delete deployment -l'
alias ksysrming='kubecolor --namespace=kube-system delete ingress'
alias ksysrmingall='kubecolor --namespace=kube-system delete ingress --all'
alias ksysrmingl='kubecolor --namespace=kube-system delete ingress -l'
alias ksysrml='kubecolor --namespace=kube-system delete -l'
alias ksysrmpo='kubecolor --namespace=kube-system delete pods'
alias ksysrmpoall='kubecolor --namespace=kube-system delete pods --all'
alias ksysrmpol='kubecolor --namespace=kube-system delete pods -l'
alias ksysrmsec='kubecolor --namespace=kube-system delete secret'
alias ksysrmsecall='kubecolor --namespace=kube-system delete secret --all'
alias ksysrmsecl='kubecolor --namespace=kube-system delete secret -l'
alias ksysrmsvc='kubecolor --namespace=kube-system delete service'
alias ksysrmsvcall='kubecolor --namespace=kube-system delete service --all'
alias ksysrmsvcl='kubecolor --namespace=kube-system delete service -l'
alias ksysrun='kubecolor --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'

function kgpl() {
  if [ -z "$1" ]; then
    echo "Usage: kgpl <pod_name>"
    return 1
  fi

  POD_NAME="$1"
  kubecolor get pod "$POD_NAME" --template='{{.metadata.labels}}'
  echo
}

function kgpln() {
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: kgpln <namespace> <pod_name>"
    return 1
  fi

  NAMESPACE="$1"
  POD_NAME="$2"
  kubecolor get pod -n "$NAMESPACE" "$POD_NAME" --template='{{.metadata.labels}}'
  echo
}

function krsj() {
  kubectl get job -n $1 $2 -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -
}
