format = """
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$helm\
$gcloud\
$openstack\
$status"""


[cmd_duration]
format = '[⏱ $duration]($style)'
min_time = 5_000

[docker_context]
format = '[$symbol$context]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
format = '[$symbol$branch]($style) '

[golang]
format = '[$symbol($version)]($style) '

[helm]
format = '[$symbol($version)]($style) '

[kubernetes]
disabled = false
format = '[$symbol$context]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[status]
disabled = false
format = '[$status]($style) '
