format = """
$hostname \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$cmd_duration\
$kubernetes\
$python
$status\
$character
"""

[cmd_duration]
format = '[⏱ $duration]($style) '
min_time = 5_000

[fill]
symbol = ' '

[git_branch]
format = '[$symbol$branch]($style) '

[golang]
format = '[$symbol($version)]($style) '

[hostname]
format = '[$hostname]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[status]
disabled = false
format = '[$status]($style) '

[time]
disabled = false
format = '[$time]($style)'
