format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status
$character"""

right_format = """$kubernetes $docker_context $time"""


[cmd_duration]
format = '[⏱ $duration]($style)'
min_time = 5_000

[docker_context]
only_with_files = false
format = '[$symbol$context]($style) '

[git_branch]
format = '[$symbol$branch]($style) '

[golang]
format = '[$symbol($version)]($style) '

[kubernetes]
disabled = false
format = '[$symbol$context]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[status]
disabled = false
format = '[$status]($style) '

[time]
disabled = false
format = '[$time]($style)'
