#!/bin/zsh

umask 022

set -o noclobber
setopt nobeep
setopt completeinword
setopt correct
setopt extended_glob
setopt hash_list_all
setopt interactivecomments
setopt noflowcontrol
setopt nonomatch
setopt noshwordsplit
setopt prompt_subst

if [ -e "$XDG_RUNTIME_DIR/gcr/ssh" ]; then
  export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"
fi

if [ -d "/home/linuxbrew/.linuxbrew/bin" ]; then
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

export BAT_THEME="cobalt2"
export EDITOR="nvim"
export HISTFILE="${HOME}/.zsh_history"
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd:cd ..:cd.."
export HISTSIZE=25000
export LESS=-R
export PAGER="less -R"
export SAVEHIST=25000
export MAKEFLAGS="-j"

export EZA_COLORS=di=34:bd=33:cd=33:so=31:ex=32:ur=33:uw=31:ux=32:ue=32:uu=33:gu=33:lc=31:df=32:sn=32:nb=32:nk=32:nm=32:ng=32:nt=32

setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Setup XDG paths and directories based off these paths
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export SWAYSHOT_SCREENSHOTS="$HOME/pictures/screenshots"
export QT_QPA_PLATFORM=wayland

export GOPATH=$HOME/.local/share/go
export GOBIN=$GOPATH/bin

path+="${GOBIN}"
path+="${HOME}/.yarn/bin"
path+="${HOME}/.cargo/bin"
path=("${HOME}/bin" "${HOME}/.local/bin" "${HOME}/.krew/bin" $path)

for i in ${HOME}/.local/share/gem/ruby/*; do
  if [ -d "$i" ]; then
    path+="$i/bin"
  fi
done

for i in ${HOME}/.gem/ruby/*; do
  if [ -d "$i" ]; then
    path+="$i/bin"
  fi
done

for i in ${HOME}/Library/Python/*; do
  if [ -d "$i" ]; then
    path+="$i/bin"
  fi
done

typeset -U PATH
export PATH
