#!/bin/zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


eval "$(zoxide init zsh)"

# My dotfiles
for i in $HOME/git/dotfiles/zsh/*.zsh; do
  source "$i"
done

if [ -f "$HOME/.zshrc_local" ]; then
  source ~/.zshrc_local
fi

# Plugins that need to be sourced last
ZVM_INIT_MODE=sourcing

if [ "$(uname)" == "Darwin" ]; then
  source "$(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme"
  source $(brew --prefix)/share/zsh-autopair/autopair.zsh
  source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh
else
  source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
  source ~/git/dotfiles/zsh/plugins/autopair.zsh
  source ~/git/dotfiles/zsh/plugins/zsh-history-substring-search.zsh
fi

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

if [ "$(uname)" == "Darwin" ]; then
  # Fix issue with man pages being slow
  typeset -gA FAST_HIGHLIGHT
  FAST_HIGHLIGHT[chroma-man]=

  export PATH="$(brew --prefix)/bin:$PATH"
fi

source ~/git/dotfiles/zsh/plugins/you-should-use.plugin.zsh
source ~/git/dotfiles/zsh/plugins/fast-syntax-highlighting.plugin.zsh

if [ $commands[atuin] ]; then
  eval "$(atuin init zsh --disable-up-arrow)"
fi

if [ $commands[rbenv] ]; then
  eval "$(rbenv init -)"
fi

typeset -U PATH

ZLE_RPROMPT_INDENT=0
[[ ! -f ~/git/dotfiles/zsh/prompt/p10k.zsh ]] || source ~/git/dotfiles/zsh/prompt/p10k.zsh
