#!/bin/zsh
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"



# My dotfiles
for i in $HOME/git/dotfiles/zsh/*.zsh; do
  source "$i"
done

if [ -f "$HOME/.zshrc_local" ]; then
  source ~/.zshrc_local
fi

# Plugins that need to be sourced last
ZVM_INIT_MODE=sourcing

if type brew &>/dev/null; then
  source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
  source $(brew --prefix)/share/zsh-autopair/autopair.zsh
  source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh
fi

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fix issue with man pages being slow
if [[ $(uname -a) = (#i)*darwin* ]] {
  typeset -gA FAST_HIGHLIGHT
  FAST_HIGHLIGHT[chroma-man]=
}

if type brew &>/dev/null; then
  source $(brew --prefix)/share/zsh-you-should-use/you-should-use.plugin.zsh
  source $(brew --prefix)/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
  export PATH="$(brew --prefix)/bin:$PATH"
fi


typeset -U PATH
